name: Java CI with Gradle

on:
  push:
    branches: [ "main", "actions" ]
  pull_request:
    branches: [ "main", "actions" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
      
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew
      working-directory: ./services/cif-service
      run: chmod +x gradlew
    
    - name: Gradle build
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
      

    # - name: Build with Gradle
      
    # steps:
    # - uses: actions/checkout@v3
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'
    # - name: path to build
    #   run: cd services/$Project_Name/
    #   env:
    #       Project_Name: cif-service
    