name: Java CI with Gradle

on:
  push:
    branches: [ "main", "actions" ]
  pull_request:
    branches: [ "main", "actions" ]

env:
    Project_Name: cif-service
defaults:
  run:
    working-directory: services/${env.Project_Name}
    

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
      
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Gradle build
      run: ./gradlew build
